- src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/Messages.properties
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementPermissionTest.java
In some contexts, it is interesting to provide authorised users a read-only access to list of failure causes.
This pull request creates a new `ViewCauses` permission, granted automatically for users having already `UpdateCauses`. When a user has this `ViewCauses` permission granted, he can access the list of existing failures.
Best regards,
Damien.
> Configurable anonymous access to the list of failure causes

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/Token.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/tokens/TokenTest.java
When I generate a mail using the `${BUILD_FAILURE_ANALYZER}` token, I want to have the possibility to display some specific text when no failure has been identified.
I have added the optional `noFailureText` option to the token for this purpose, with a default value set to empty.
When using `${BUILD_FAILURE_ANALYSER, noFailureText="No problem has been identified. Please contact xxx for more information"}`, the macro will expand into _No problem has been identified. Please contact xxx for more information_ if no failure has been identified.
> Having the token expand into some text when no failure cause is identified

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/CoreDBF.java
Looked at the code for getting downstream builds and found this method that did not return anything, ever. Changed the returned statement to the way I think it should be. Have not tested the code.
> Returning found builds

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/BuildFlowDBF.java
In certain cases, the Build Flow plugin can return a CancellationExcpetion
when iterating over downstream builds.
This has the effect of breaking both the Job and Build UIs.
This PR protects against this and [FIXES JENKINS-25396]
It is also related to JENKINS-32144 and JENKINS-25092
> Prevent breakage involving build-flow plugin

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
Set the name of the current thread in the thread pool to
the cause and indication currently being scanned for
to get some more useful information out of a running Jenkins.
> Set the name of the current threadpool worker

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/Statistics.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/StatisticsLogger.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/EmbeddedMongoStatisticsTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseTest.java
I often use a build/run's displayName property to store additional information about the build, like the full version number of the project being built. This information would be nice to have stored in MongoDB along with all of the other build information that is stored.
> Add displayName to stored statistics

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/IndicationAnnotatorFactory.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction.java
squid:S1155 - Collection.isEmpty() should be used to test for emptiness. 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Faisal Hameed
> Code quality fix - Collection.isEmpty() should be used to test for emptiness.

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/TimeSeriesChart.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseColumn.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/BuildFlowDBF.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTask.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1481 - Unused local variables should be removed.
squid:S1068 - Unused private fields should be removed.
squid:S1488 - Local Variables should not be declared and then immediately returned or thrown.
https://dev.eclipse.org/sonar/rules/show/squid:S1481
https://dev.eclipse.org/sonar/rules/show/squid:S1068
https://dev.eclipse.org/sonar/rules/show/squid:S1488
Faisal Hameed
> General code quality fix-2

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/Semaphore.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/ComputerGraphAction.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/Statistics.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/SemaphoreTest.java
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:MissingDeprecatedCheck - Deprecated elements should have both the annotation and the Javadoc tag.
squid:S1700 - A field should not duplicate the name of its containing class.
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:MissingDeprecatedCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1700
Faisal Hameed
> General code quality fix-4

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
This page should not refresh automatically as form contents can be lost (when adding a new failure cause).
> Set norefresh=true for this layout.

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/KnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/utils/OldDataConverter.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
squid:S3400 - Methods should not return constants.
squid:S2178 - Short-circuit logic should be used in boolean contexts.
https://dev.eclipse.org/sonar/rules/show/squid:S2864
https://dev.eclipse.org/sonar/rules/show/squid:S3400
https://dev.eclipse.org/sonar/rules/show/squid:S2178
Faisal Hameed
> General code quality fix-3

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtension.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtensionTest.java
Previous way to escape single quote didn't work. Now I added test and fixed it.
> Escape single quote correctly

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtension.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseDisplayData.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtensionTest.java
Before BFA parsed only top level build and first nested build. This
commit introduces recursion for parsing all downstream builds.
I wrote unit tests to verify this behaviour on GerritMessageProviderExtension side.
Also I fixed a bug introduced in my previous PR (https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/54/files#diff-9bf284a9e0f5bafa28fce3ecc91c362aR84): gerrit used run url from top build - instead of build there error occurs.
And implemented new replacement for single comma `. Not it's replaced on equal HTML code.
p.s. I created this PR to show that my previous fix didn't help and even make some stuff worse. I tested it in non-production environment and didn't notice it. So, in case of this PR I think we need to wait at least Monday then I will have some feedback …
> Fix gerrit feedback for nested builds

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.properties
The displayed message in the configuration screen doesn't show the blank between the 2 words before and after the line break ("...found causesto the Gerrit-Trigger-plugin..."). Interestingly enough, I fixed a similar issue in Eclipse JDT code recently, so maybe the behaviour of the JVM changed here?
> Fix line break

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/Indication.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/MultilineBuildLogIndication.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReaderTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/MultilineBuildLogIndicationTest.java
This fork provides some needed MultiLineBuildLogIndication
performance and bug fixes (see commit messages for more details):
**JSON Serialization**
Since inherited classes from Indication does not declare
@JsonProperty("pattern") in their constructors, the JSON
writer will use the default constructor and populate fields
using a matching (by name) getter.
This leads to one particular bad bug, where
MultiLineBuildLogIndication returns a faulty modified pattern
using the @Overidden getPattern() during JSON serialization.
**Performance fixes.**
Test data:
Log: 49MB log @ 280.000 lines
Multiline pattern: Simple pattern, matching +20 lines at end of log
**Pre-fix: 32 seconds** (Note that the hardcoded timeout is 10 seconds)
**Post-fix: 1.7 seconds**
**Multiline patterns could only match …
> MultiLineBuildLogIndication performance and bug fixes

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtension.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtensionTest.java
Now BFA reports something like "No problems were identified..." if there is no matches. But in case of gerrit feedback it doesn't send anything, so, user should click on feedback and discover failed child job by himself.
I think we can easily simplify this case by providing at least failed build directly to Gerrit. How it would be in Gerrit:
> Send "unknown" to Gerrit if no bfa patterns were found

- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/providers/FailureCauseProvider.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/TokenUtils.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseProviderTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtensionTest.java
The MQ Notifier plugin sends messages to a Message Queue,
implementing the AMQP protocol, e.g. RabbitMQ, whenever a
build is finished.
The plugin allows for other plugins to add
information to the message. This commit adds support for
the Build Failure Analyzer to supply Failure Cause information
from the build.
The dependency to the MQ Notifier plugin is made optional.
> Added a FailureCauseProvider for the MQ Notifier plugin

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/providers/FailureCauseProvider.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseProviderTest.java
The found indications was only a single indication,
it is now a list.
Also, the ID of the failure cause was the key of each
failure cause, it has been moved inside the failure cause
structure.
> Corrected JSON structure of RabbitMQ message

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/DisplayDownstreamTest.java
Current implementation of method compareTo of Run is not alighed with method `equals`.
As result `compareTo` for builds from different parents, but with same number, returns 0.
And TreeSet as any sorted set keeps only one build instead of two.
https://github.com/jenkinsci/jenkins/pull/2762
> Fix collecting downstream builds

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
The `PluginImpl.configure` method does not use the correct field for parsing the `threadKeepAliveTime` variable.
> Correction of parsing for `threadKeepAliveTime` variable

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.properties
The maximum log size is very useful must the unit being used was not clear. I've added the unit in the description of the field.
> Specify the unit for the log size maximum (MB according to the code)

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication/help-userProvidedExpression.html
Since I have seen quite a lot of confusion regarding how
the regular expression matching works for BuildLogIndications,
I added some extra information on this.
> Clarified how the regular expression matching works

- src/main/resources/META-INF/hudson.remoting.ClassFilter
It is a plan C fix, which does not include PCT Compatibility (#81) and which does not wait for adding these entries on the core side (https://github.com/jenkinsci/jenkins/pull/3234).
https://issues.jenkins-ci.org/browse/JENKINS-48932
@reviewbybees @rsandell
> [JENKINS-48932] - Whitelist extra java.util.Collection classes being used in BFA

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction/summary.groovy
FailureCauseBuildAction displays HTML properly (like bold text or paragraphs) while FailureCauseMatrixBuildAction displays plain text. So I just propose using the same formatting for cause descriptions in both templates.
> Display HTML for cause description in matrix

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/ProjectGraphAction.java
Using Windows and matrices, some project names include backslashes that cause exceptions in onCompleted method. Other Regex special characters could be present so Pattern.quote avoids the whole problem!
> Escape regex special chars in project full name

- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/Token.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/tokens/PipelineTokenTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/tokens/TokenTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/tokens/TokenUtilsTest.java
This PR adds the functionality to call Build Failure Analyzer from a pipeline by using the Token Macro Plugin's [`tm` pipeline step](https://jenkins.io/doc/pipeline/steps/token-macro/) that was added in v2.0, for example:
```groovy
tm 'BUILD_FAILURE_ANALYZER'
```
This pipeline step is using a new overload of `evaluate` so if you try to call it with the build failure analyzer token it won't run and it will return a message like:
> BUILD_FAILURE_ANALYZER is not supported in this context
The changes in this PR implements that overload:
```groovy
echo tm('BUILD_FAILURE_ANALYZER')
```
Output:
>[Pipeline] tm
>[BFA] Found failure cause(s):
>[BFA] Backend Compilation Error from category Backend
>[BFA] Done. 0s
>[Pipeline] echo
>Identified problems:
>* Backend Compilation Error: A build failure …
> Add support for Token Macro tm pipeline step

- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/BuildCacheDBF.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/DisplayDownstreamTest.java
The downstream-build-cache-plugin (https://plugins.jenkins.io/downstream-build-cache) already creates a map of downstream upstream relationships.
We can make use of that cache for finding downstream dependencies, which also works for pipeline downstream dependencies (https://issues.jenkins-ci.org/browse/JENKINS-22026)
> New DownstreamBuildFinder using build-cache-plugin

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.properties
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
Allows to designate categories as fallback. When scanning for
known causes, fallback causes are only stored if there are no non-fallback
causes present.
Use case:
- fallback cause: A maven goal failed
- specific cause: The code did not compile
Old behaviour: Both causes would be shown, leading to descriptions like
"always look for more specific causes first"
New behaviour: if a compile error is found, only that one is shown
(maven error is ignored as fallback). Otherwise, the information that
the failure was due to a maven error (along with the link!) is still
provided.
> New feature: fallback causes

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause/index.groovy
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
This fixes the 'umlauts' problem (https://issues.jenkins-ci.org/browse/JENKINS-47027) which seem to be a result of wrong encoding of umlauts in +`encode()`.
By using POST instead of GET (and switching to default Descriptor based validation), we circumvent that problem.
- I moved the validation methods into the Descriptor (default behaviour)
- change the validation to POST
- Changed `FailureCauseHudsonTest` from legacy `HudsonTestCase` to using the newer `JenkinsRule` (I needed access to the WebResponseListener)
> [JENKINS-47027] fix umlauts

- pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9
> update jackson from 2.9.3/2.9.7 to 2.9.9 CVE-2019-12086

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/KnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/StatisticsLogger.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase/config.jelly
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/jcasc/ConfigurationAsCodeMongoTest.java
Since 1.23, the saving of the BFA configuration is broken.
The KnowledgeBase is always overwritten.
In a LocalKnowledgeBase, this causes all causes to be removed.
In a MongoDBKnowledgeBase:
The getters for enabling statistics and successfullogging stats
were wrongly named, causing the databinding to be broken.
JENKINS-59610
JENKINS-59593
> [JENKINS-59610 JENKINS-59593] Fixed configuration issues introduced in 1.23

- pom.xml
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
To fix security warning that GitHub irritatingly shows me all the time.
The new version of jackson-api plugin requires a new Jenkins core for unknown reason.
Also fixes a checkstyle error introduced in #112
> Bump jackson2 to 2.10.0 

- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/EmbeddedMongoTest.java
When I run `mvn test` in this project, my computer collapses during execution of `EmbeddedMongoStatisticsTest` (it becomes awfully unresponsive, to the point of requiring a hard reboot). It seems to be because too many `mongod` processes are running: I've seen 10 of them during an execution of `EmbeddedMongoStatisticsTest`, before I interrupted Maven (while the computer was getting unresponsive already but still usable). I have no idea why "only" 10 MongoDB processes are an issue at all, but anyway, I thought it would be good to avoid that.
This PR fixes the issue by adding an `@After`-annotated method to the abstract `EmbeddedMongoTest` class. It was certainly missing, because in the `@Before` a MongoDB process is forked, which was never explicitly stopped.
> stop the MongoDB processes forked in tests

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
In the plugin global configuration, several boolean options (checkboxes) are not working: when you change their value via the GUI, save, and reload the configuration page, their state is actually not changed.
A good way to test them all is the following:
- tick all checkboxes, save, reload, see some checkbox are still unticked
- untick all checkboxes, save, reload, see some checkbox are still ticked
The only boolean option which works is `doNotAnalyzeAbortedJob`.  The four other ones (`graphsEnabled`, `globalEnabled`, `testResultParsingEnabled`, `gerritTriggerEnabled`) are broken.
I think this bug has been introduced by recent JCASC changes, more precisely by the adoption of `StaplerRequest#bindJSON(Object,JSONObject)` to replace the many explicit `something = o.getBoolean("something")` …
> Fix boolean options in plugin global config

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction/summary.groovy
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction/summary.groovy
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/TransientCauseManagementHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseActionTest.java
When a build fails and no build causes in the knowledge base are
matched against the console log, the build page reports with an
heading and a message that there was "No identified problem".
While most users would understand the message, we had reports
from the developers reporting that the message is very confusing,
in particular in the early stages after the plugin is deployed,
and the knowledge base does not include many frequent failures.
This patch introduces a global switch that lets the administrator
turn off the display of the build analyzer block on build pages
of jobs that failed and no indication was found.
> Add a global switch to disable report when no causes identified

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
It didn't seem to matter, at least for JCasC, but something must have not worked properly.
> Fixed some missed data binding annotations in global config

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
Without this change including the latest version of BFA as a plugin dep requires dependency management to be added to manage conflicts from `mongojack`, one of the pipeline plugins and `jackson2-api` plugin
Previously:
```
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>${jackson.version}</version>
</dependency>
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<version>${jackson.version}</version>
</dependency>
</dependencies>
</dependencyManagement>
<dependencies>
<dependency>
<groupId>com.sonyericsson.jenkins.plugins.bfa</groupId>
<artifactId>build-failure-analyzer</artifactId>
<version>1.24.0</version>
<optional>true</optional> …
```
> Fix jackson deps and incrementalise

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/providers/FailureCauseProvider.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseProviderTest.java
The line number is needed for allowing us to figure out which
indicator was found first.
Note: In this PR, the linenumber will only be provided for single
line indicators. While it may be feasible to add line counting to
the multiline indicators, it's a complemetely different beast. The
multiline implementation uses a sliding search window mechanism and
line counting will incur some refactoring. If ever needed, it should
be added in a future PR.
> Include line number of the found indication data

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/Statistics.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/GerritMessageProviderExtensionTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/SlackMessageProviderTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/EmbeddedMongoStatisticsTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBaseTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTaskTest.java
Add Failure Categories to Slack message.
Add Failure Description to slack message.
Improve UI.
Fix a case where you end up getting information about two failing cases when you are only looking to get messages for one.
Remove deprecated
java.util.concurrent.Future;
in favor of
hudson.model.queue.QueueTaskFuture;
Improve slack Message unit tests
An example of multiple categories for a Cause:
An example of multiple Failures in one message:
> Add Categories to Slack message improve UI and fix deprecations

- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseWorkFlowTest.java
In PR #103 the scope was changed for workflow jobs (and others) to
carry out the BFA analysis in RunListener.onFinalized() scope due
to JENKINS-42755.
I argue that this was the wrong way to remedy the mentioned issue
due to following factors:
1. RunListener.fireCompleted() is executed before a build is
released. When we say 'released' we mean that any waiting upstream
builds can continue (or downstream builds can be triggered).
2. RunListener.fireFinalized() is executed after the build has
been released.
The Build Failure Analyzer plugin was originally written to be
executing in RunListener.onCompleted() scope and then wait for the
analysis to be completed. This means that the waiting upstream
build will wait for its downstream builds to complete (and be
analysed) before doing its own …
> Analyze all projects in RunListener.onCompleted() scope (again)

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
The constructor of class `FailureCause` `FailureCause(String name, String description, String comment, String categories)` is not passing the argument `comment` to the overloaded constructor.
> Fix FailureCause constructor not passing comment argument

- README.md
- docs/metrics.md
- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManager.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FoundFailureCause.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/IFailureCauseMetricData.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManagerTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBaseTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTaskTest.java
This adds integration with the Metrics plugin to replace the graphs that were removed by version 2, this will allow users to integrate with there own metrics systems (e.g. Prometheus or Data Dog).
This uses a counter from the Metrics library which will reset when jenkins is restarted which was done for implementation simplicity.
> Integration with the Metrics plugin

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseCache.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseCacheTest.java
See https://issues.jenkins.io/browse/JENKINS-67238
This ensures that even before the Mongo KnowledgeBase is started that calls to get the causes and categories will not NullPointer.
Ideally the starting of new knowledge bases set through casc should also be addressed. However this is problematic in terms of maintaining the current functionality.
With casc the setKnowledgeBase method on the plugin is called to swap the knowledge bases. However a lot of functionality is coded in the configure method which is called when a UI config update has occurred. Attempting to move the code to start new knowledge bases into the code that is called when casc is used to update causes a lot of test failures. It is difficult to maintain the reverting to the previous knowledge base when the new one fails …
> JENKINS-67238 ensure that we can retrieve causes and categories before the updater has run.

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManager.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.properties
- src/main/webapp/help/help-metricSquashingEnabled.html
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManagerTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/jcasc/ConfigurationAsCodeLocalTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/jcasc/ConfigurationAsCodeMongoTest.java
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local-expected.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo-expected.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo.yml
"Squash failure metrics to unique categories for each build" option can be useful when a single failed build should count towards each cause category exactly once. 
This is particularly useful when combined with the "Treat failed  test cases as failure causes." If numerous tests fail, "squash failure metrics" will prevent those categories from being incremented for every single failed test, which can skew metrics significantly.
> Add metric category squashing per build feature

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase/config.jelly
Starting with MongoDB 4.2 compatible drivers, retryable writes is enabled by default. However, Amazon DocumentDB does not currently support retryable writes. I am adding a support to enable/disable that setting while using this plugin
Options
> [JENKINS-66014] Adding support  retryable writes.

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java
Current line should only be increased when we
advance one line in the log, but now it is
increased:
(every line * total number of indications)
> Fix: Broken line counting

- src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.
Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @rsandell 
Thanks in advance!
> Adapt icon removal from core

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FoundFailureCause.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
I'd like to access information about failure causes from Jenkins API.
> Export some fields about the found failure cause indication

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseTest.java
The host setting can now be input as a list of hosts, separated
by a comma. For everyone just inputting one host, there is no change
in functionality.
Made getMongoConnection in MongoDBKnowledgeBase package-private for
testing purposes.
> Added multi node support for MongoDB

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandVariables.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/jcasc/ConfigurationAsCodeLocalTest.java
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local-expected.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo-expected.yml
- src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo.yml
As shown in JENKINS-70489, an IllegalArgumentError is thrown when scanning builds on demand.
This is because the Java 11 version of ThreadPoolExecutor is more picky with input values, making sure that corePoolSize < maximumPoolSize. This commit fixes our input values to make sure the above is true.
> Fix ScanOnDemandVariables for Java 11 ThreadPoolExecutor.

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseTest.java
Either when you click the "Test Connection" button, or switch from a MongoDBKnowledgeBase, connection threads towards the old one are left hanging around. These won't get removed until the Jenkins server is restarted.
This commit makes sure that the connection is closed, which also remove the threads.
> Fix for leaking threads when closing a MongoDBKnowledgeBase

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/ScanLogAction.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
https://issues.jenkins.io/browse/JENKINS-72474
Additional informations on `ScanLogAction` for plugins to know the current scan status:
- startTime
- endTime
- exceptionMessage
```[tasklist]
```
> [JENKINS-72474] Additional informations on BFA scans

- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/MultilineBuildLogFailureReader.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReaderTest.java
Changed the reader for multli-line pattern scan from BufferedReader to **LineNumberReader** which is a subclass of BufferedReader that adds the feature of counting lines for all read operations, which can then be used to **set matching line for the found indication**.
```[tasklist]
```
> Add line matching for multi-line pattern parse

- Jenkinsfile
- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementPermissionTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseHudsonTest.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
Subsumes #181. Allow this plugin's test suite to be exercised regularly in Plugin Compatibility Tester (PCT) in https://github.com/jenkinsci/bom by requiring Java 17 or newer and Jenkins 2.475 (released today) or newer.
This PR goes against the usual advice from https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ by requiring a weekly release. The advantage is that this will allow plugin compatibility testing (PCT). The disadvantage is that new features and bug fixes can't be released to LTS users for another few months.
The choice is up to the maintainer as to whether or not to accept this PR. If this PR is rejected, we will stop testing this plugin in PCT.
> Require Java 17 and 2.475; adapt test suite to EE 9

- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseHudsonTest.java
When attempting to add this plugin to `jenkinsci/bom` (since it is a dependency of 4 other Jenkins plugins), I found that these two tests failed to run in recent versions of HtmlUnit. The problem seems to be related to `NicelyResynchronizingAjaxController`, as I no longer experienced any issues with the default `AjaxController`. Since JavaScript is now running asynchronously, I added a barrier to ensure that asynchronous activity is complete by the time we make the assertions.
Tested before and after the upgrade to the latest HtmlUnit. Before, the tests only passed on the old version of HtmlUnit. After, they pass on both old and new versions of HtmlUnit.
> Forward compatibility with recent versions of HtmlUnit

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/workflows/jenkins-security-scan.yml
- .github/workflows/release-drafter.yml
- .gitignore
- .mvn/extensions.xml
- Jenkinsfile
- pom.xml
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/IndicationAnnotatorFactory.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/Indication.java
- src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction.java
- src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseProjectActionHudsonTest.java
Complete the migration started in #182.
`mvn clean verify`
> Refresh plugin for October 2024
