src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseColumn/columnHeader.jelly
instead of cropping it to min width
=> This makes error message readable on List View

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.properties
missing blank between two words on different lines
=> Language fix

src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
Hotfix for issue ticket [JENKINS-30643].
=> [JENKINS-30643] Hotfix for MongoDB statistics configuration.

README.txt
Another test to see if PR's are accepted :). I had a hard time navigating without these urls.
=> DOC: Add Issues, Plugin main page URL to Readme.txt; Regex Question.

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction/index.jelly
Each of these stood out to me while using the plugin as being off.
=> Formatting fixes

src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
squid:S2095 - Resources should be closed.
https://dev.eclipse.org/sonar/rules/show/squid:S2095
Faisal Hameed
=> Code quality fix - Resources should be closed.

src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTask.java
squid:S1066 - Collapsible "if" statements should be merged.
squid:S1905 - Redundant casts should not be used
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S1905
Faisal Hameed
=> General code quality fix-1

src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/BarChart.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/ComputerGraphAction.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/PieChart.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/ProjectGraphAction.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTask.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/StatisticsLogger.java
squid:S1854 - Dead stores should be removed. 
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Faisal Hameed
=> Code quality fix - Dead stores should be removed.

Jenkinsfile, pom.xml, src/test/java/com/sonyericsson/jenkins/plugins/bfa/DisplayDownstreamTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseProjectActionHudsonTest.java
Same as #76 except, well, filed by me. :-)
=> Add Jenkinsfile to enable CI testing

src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
usage of PluginImpl.getInstance in the static field can result in an exception if the plugin is not registered at the time of the call.
In the best case, the plugin is not started. In the worst one, it crashes the initialization thread, and Jenkins will wait for it forever (Jenkins core should be modified to handle this case gracefully).
=> ensure PluginImpl will be ready when initializing the threadpool

Jenkinsfile, pom.xml, src/main/java/com/sonyericsson/jenkins/plugins/bfa/BfaGraphAction.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/GraphCache.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/graphs/GraphType.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/DownstreamBuildFinder.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/dbf/ParameterizedTriggerDBF.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandQueue.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/Renderer.java, src/main/resources/META-INF/hudson.remoting.ClassFilter, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseColumn/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/ScannerJobProperty/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication/config.jelly, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/indication/MultilineBuildLogIndication/config.jelly, src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementPermissionTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/DisplayDownstreamTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseMatrixAggregatorTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/TransientCauseManagementHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseColumnTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndicationTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/MultilineBuildLogIndicationTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/test/utils/JenkinsRuleWithMatrixSupport.java
I was trying to make the plugin runnable with PCT in order to have a test suite for https://issues.jenkins-ci.org/browse/JENKINS-48932 . The codebase is pretty obsolete, and the tests hang on my machine IIUC. Let's see whether tests pass in CI.
@reviewbybees @rsandell
=> [JENKINS-48932] - Update plugin to make it runnable with PCT

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
Follow discussion from [#3449 in core](https://github.com/jenkinsci/jenkins/pull/3449)
@dobbymoodge
=> Improve support for sortable.js

pom.xml
In preparation for configuration as code plugin support
=> JENKINS-54439 Upgrade jenkins baseline

src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication.java
Issue fixing:
https://issues.jenkins-ci.org/browse/JENKINS-54839
Happy to look into writing a test case for this?
But its a simple change and it probably would require lots of wrangling with enforcer plugin to get the needed test dependencies in here to reproduce it?
=> JENKINS-54839 Make match text work for PRs in multibranch github pipeline

src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
When trying to connect with no authentication I was having issues with the jenkins UI created a secret with an empty string in it
After this change I can connect successfully
=> Add empty check to password

src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndication.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/Indication.java, src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/MultilineBuildLogIndication.java
https://issues.jenkins-ci.org/browse/JENKINS-55110
See:
https://github.com/mongojack/mongojack/issues/157#issuecomment-336479449
=> JENKINS-55110 Fix deserialisation for mongo

src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
Previously it was always showing connection ok
Testing connection properly now with a ping:
https://stackoverflow.com/a/40690891
Fixed:
=> JENKINS-57812 Fix test connection

LICENSE, README.md
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>
=> Adding LICENSE file and editing License section of README.md

pom.xml, src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
Use the versions of Mockito and PowerMock as defined in the parent.
Update other plugins and code as required by the newer versions.
=> Upgrade parent pom

pom.xml
=> bump jackson2-api to 2.10.2

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction/summary.groovy
This suggested (mostly minimal) pull-request will fix the NPE as discussed in https://issues.jenkins-ci.org/browse/JENKINS-60153
=> [JENKINS-60153] Fix NullPointerException

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction/summary.groovy, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction/summary.groovy
- use new style classes to override heading tags
=> Fix large font-sizes after Jenkins Typography changes

pom.xml, src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
To manage plugin dependencies.
=> Configure BOM

pom.xml
What happens if I remove it?
It has been in scope: provided all along so it hasn't been packaged with the plugin and used the version in core all along. With the removal of statistics we might not even be using it at all any more.
=> Remove guava dependency

Jenkinsfile, pom.xml, src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
=> Bump plugin parent, jenkins core and bom.

findbugs-exclude.xml, pom.xml, src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementPermissionTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/TransientCauseManagementHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseColumnTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseHudsonTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/BuildLogIndicationTest.java, src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseActionTest.java
=> Refresh plugin for June 2023

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
As described in JENKINS-73028, the remove link isn't currently working, this PR fixes it.
Created a failure cause, clicked the remove link which was previously not working and saw that it now works.
```[tasklist]
```
=> Fix link for removing causes from the management page

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/remove.groovy, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/resource.js, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction/ScanMode/index.groovy, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseAction/ScanMode/resource.js
https://issues.jenkins.io/browse/JENKINS-74893
[Before the change](https://www.youtube.com/watch?v=31N5ox9TF8s)
[After the change](https://www.youtube.com/watch?v=iCO792CHWOo)
=> [JENKINS-74893] Extract inline JavaScript event handlers

src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy, src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/remove.groovy
=> Migrate from EE 8 to EE 9 in Groovy views
